# These are supported funding model platforms
<iframe src="https://github.com/sponsors/Gatito1010/button" title="Sponsor Gatito1010" height="35" width="116" style="border: 0;"></iframe>
github: [louistiti]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # http://sponsor.getleon.ai
